sistemaPerguntasWeb/sistemaPerguntasWeb/Models/Legislacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace sistemaPerguntasWeb.Models
{
	public class Legislacao
	{
		public int IDLegislacao { get; set; }
        public int IDAluno { get; set; }
        public string Tema { get; set; }
		public int QuantidadeAulasParaOTema { get; set; }
        public List<ComentarioLegislacao> Comentarios { get; set; }

    }
}

sistemaPerguntasWeb/sistemaPerguntasWeb/Models/Perguntas.cs
    using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace sistemaPerguntasWeb.Models
{
    public class Perguntas
    {
        public int ID { get; set; }
        public string Corpo { get; set; }
        public string OpcaoA { get; set; }
        public string OpcaoB { get; set; }
        public string OpcaoC { get; set; }
        public string OpcaoD { get; set; }
        public string Certo { get; set; }
    }
}

sistemaPerguntasWeb/sistemaPerguntasWeb/Controllers/PerguntasController.cs
using sistemaPerguntasWeb.App_Start;
using sistemaPerguntasWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace sistemaPerguntasWeb.Controllers
{
    public class PerguntasController : Controller
    {
        // GET: Perguntas
        public ActionResult Legislacao()
        {
            return View(TrazAsPerguntas());
        }
        [HttpPost]
        public JsonResult Legislacao(string inputs)
        {
            int pontos = 0;

            var valorLimpo = inputs.Replace('[', ' ').Replace(']', ' ').Replace('"', ' ').Replace(',', ' ').Replace(" ", "");
            var respostas = TrazAsPerguntas();
            for (int i = 0; i < valorLimpo.Length; i++)
            {
                var selecao = valorLimpo.Substring(i, 1);
                if (respostas[i].Certo == selecao.ToString())
                {
                    pontos ++;
                }
            }
            var resultado = (pontos >= 21) ? true : false;
            return Json(resultado);
        }
        public List<Perguntas> TrazAsPerguntas()
        {
            List<Perguntas> perguntas = new List<Perguntas>();
            var command = SQL.GetDataSet("SELECT * FROM Perguntas");
            for (int i = 0; i < 30; i++)
            {
                perguntas.Add(new Perguntas());
                perguntas[i].ID = (int)command.Tables[0].Rows[i]["ID"];
                perguntas[i].Corpo = command.Tables[0].Rows[i]["Corpo"].ToString();
                perguntas[i].OpcaoA = command.Tables[0].Rows[i]["OpcaoA"].ToString();
                perguntas[i].OpcaoB = command.Tables[0].Rows[i]["OpcaoB"].ToString();
                perguntas[i].OpcaoC = command.Tables[0].Rows[i]["OpcaoC"].ToString();
                perguntas[i].OpcaoD = command.Tables[0].Rows[i]["OpcaoD"].ToString();
                perguntas[i].Certo = command.Tables[0].Rows[i]["RespostaCerta"].ToString();
            }
            return perguntas;
        }
    }
}

sistemaPerguntasWeb/sistemaPerguntasWeb/Views/Perguntas/Legislacao.cshtml
@model List<Perguntas>
@{
    ViewBag.Title = "Legislação";
    ViewBag.Page = "Quiz";
    Layout = "../Shared/_LayoutLogin.cshtml";
}
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle"></h5>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer"></div>
        </div>
    </div>
</div>
<h2 id="sessao" class="pull-right"></h2>
<div class="container">
    @*@using (Html.BeginForm("Legislacao", "Perguntas", FormMethod.Post))
        {}*@
    <form>
        @{
            int pri, seg, ter, qua, i = 1, j = 0;
            foreach (var pergunta in @Model)
            {
                pri = j;
                seg = j + 1;
                ter = j + 2;
                qua = j + 3;
                <fieldset id="field-@i">
                    <div style="background:#fff;border:1px solid lightgray; border-radius:6px;padding:1em;">
                        <div class="funkyradio col-xl-12">
                            <p>@i ) @pergunta.Corpo</p>
                            <div class="funkyradio-default">
                                @*@Html.RadioButton("radio-" + i, "a", false, new { @id = "radio-" + pri })
                                    @Html.Label(pergunta.OpcaoA, new { @for = "radio-" + pri })*@
                                <input type="radio" name="radio-@i" id="radio-@pri" value="A" />
                                <label for="radio-@pri">@pergunta.OpcaoA</label>
                            </div>
                            <div class="funkyradio-default">
                                @*@Html.RadioButton("radio-" + i, "b", false, new { @id = "radio-" + seg })
                                    @Html.Label(pergunta.OpcaoB, new { @for = "radio-" + seg })*@
                                <input type="radio" name="radio-@i" id="radio-@seg" value="B" />
                                <label for="radio-@seg">@pergunta.OpcaoB</label>
                            </div>
                            <div class="funkyradio-default">
                                @*@Html.RadioButton("radio" + i, "c", false, new { @id = "radio" + ter })
                                    @Html.Label(pergunta.OpcaoC, new { @for = "radio" + ter })*@
                                <input type="radio" name="radio-@i" id="radio-@ter" value="C" />
                                <label for="radio-@ter">@pergunta.OpcaoC</label>
                            </div>
                            <div class="funkyradio-default">
                                @*@Html.RadioButton("radio" + i, "d", false, new { @id = "radio" + qua })
                                    @Html.Label(pergunta.OpcaoD, new { @for = "radio" + qua })*@
                                <input type="radio" name="radio-@i" id="radio-@qua" value="D" />
                                <label for="radio-@qua">@pergunta.OpcaoD</label>
                            </div>
                        </div>
                    </div>
                </fieldset>
                i++;
                j += 4;
            }
            <br>
            <h2 id="sessao" class="pull-right"></h2>
            <button type="submit" class="btn btn-primary pull-right">Finalizar</button>
        }
    </form>
</div>